export type User =
    {
        id: number,
        is_bot: Boolean,
        first_name: String,
        last_name: String,
        username: String,
        language_code: String,
        can_join_groups: Boolean,
        can_read_all_group_messages: Boolean,
        supports_inline_queries: Boolean
    }

  export  type Chat = {
        id: number,
         type: String,
         title: String,
         username: String,
         first_name: String,
         last_name: String,
         photo: File,
         bio: String,
         description: String,
         invite_link: String,
         pinned_message: String,
         permissions: String,
         has_protected_content: Boolean,
         linked_chat_id: number,
         location: String
        }


        export type Message ={
            message_id: number,
             from: User,
             sender_chat: string,
             date: number,
             chat: string,
             forward_from: User,
             forward_from_chat: string,
             forward_from_message_id: number,
             forward_signature: String,
             forward_sender_name: String,
             forward_date: number,
             is_automatic_forward: Boolean,
             reply_to_message: Message,
             via_bot: User,
             edit_date: number,
             has_protected_content: Boolean,
             media_group_id: String,
             author_signature: String,
             text: String,
             entities: string,
             animation: Animation,
             audio: string,
             document: Document,
             photo: string,
             sticker: string,
             video: string,
             video_note: string,
             voice: string,
             caption: String,
             caption_entities: string,
             contact: string,
             dice: string,
             game: string,
             poll: string,
             venue: string,
             location: Location,
             new_chat_members: string,
             left_chat_member: User,
             new_chat_title: String,
             new_chat_photo: string,
             delete_chat_photo: Boolean,
             group_chat_created: Boolean,
             supergroup_chat_created: Boolean,
             channel_chat_created: Boolean,
             message_auto_delete_timer_changed: string,
             migrate_to_chat_id: number,
             migrate_from_chat_id: number,
             pinned_message: Message,
             invoice: string,
             successful_payment: string,
             connected_website: String,
             passport_data: string,
             proximity_alert_triggered: string,
             voice_chat_scheduled: string,
             voice_chat_started: string,
             voice_chat_ended: string,
             voice_chat_participants_invited: string,
             reply_markup: string
            }